name: My first Action Event Push in specific branch
on:
  push:
    branches:
      - feature/my-first-action

jobs:
  hello-action:
    name: 🚀 hello my first action
    runs-on: ubuntu-latest
    steps:
      - run: echo "hello word"